### ISSUE TITLE
nginx deployment is not working as the documentation describes. 

### ISSUE THREAD

**Issue by doyoungim999** [ibm-cloud-docs/terraform#27]
https://cloud.ibm.com/docs/terraform?topic=terraform-redhat#deploy_app
-------
1. type was changed to "NodePort"
-------
spec:
  clusterIP: 172.30.132.135
  externalTrafficPolicy: Cluster
  ports:
  - name: 8080-tcp
    nodePort: 30130
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    nodePort: 30590
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: nginx
    deploymentconfig: nginx
  sessionAffinity: None
  type: NodePort
------------------------
2. Name and PORT is not same as the doc is show. 

[root@IBM-OCP-e2934d8a8b-master-0 ~]# oc get routes
NAME      HOST/PORT                                           PATH      SERVICES   PORT       TERMINATION   WILDCARD
nginx     nginx-doysfirstproject.apps.169.48.215.230.xip.io             nginx      8080-tcp                 Non

-------------------
3. the browser shows 403 fobidden error . 
I am wondering the documentation is correct.

**Comment by doyoungim999** [comment]
There is no problem if  I deploy from "openshift catalog" from the broswer".
I think documentation need to be updated.

**Comment by Nadine2016** [comment]
@doyoungim999 First of all I need to apologize for the very late response and I am very sorry to hear that you had issues accessing your app. We made a couple updates to the documentation since July and from what I can tell today, it works as it is currently documented. What is the current status of your app? Were you able to deploy and access it? Let me know if you have questions or other issues that you want us to investigate. Again, apologies for the late response!!

**Comment by Nadine2016** [comment]
closing. feel free to reopen if there is still an issue.
