### ISSUE TITLE
ibm_iam_service_policy examples are outdated

### ISSUE THREAD

**Issue by Mallear** [ibm-cloud-docs/terraform#49]
Hello,

ibm_iam_service_policy examples are outdated as resource is now a block and not a list of object. De facto resource data type should be updated to block.

**Comment by Nadine2016** [comment]
@Mallear thanks for your comment. Could you clarify if what you are referring to is: 

```
resources {
    service              = "kms"
    region               = "us-south"
    resource_instance_id = element(split(":", ibm_resource_instance.instance.id), 7)
  }
```

instead of using 
```
resources = [{
    service              = "kms"
    region               = "us-south"
    resource_instance_id = "${element(split(":",ibm_resource_instance.instance.id),7)}"
  }]
```

?

If so, this is the new syntax for Terraform v0.12. The entire Terraform docs are not updated for that yet. We have however a PR waiting already to get merged, but we wanted to wait until Schematics officially supports Terraform v0.12 as well, which is planned for end of March. Let me know if that was what you were referring to or something else. 

Thank you so much

**Comment by Mallear** [comment]
@Nadine2016, yes that's what I was reffering to. I didn't checked if this was linked to the provider or Terraform, sorry.

**Comment by Nadine2016** [comment]
@Mallear oh no worries at all. You might run into similar issues until we merge this PR in. I am very sorry for the inconvenience and the confusion that this causes. We have this issue here for it already https://github.com/ibm-cloud-docs/terraform/issues/36 I kept it open until we merge the PR in. If it is ok with you, I would close your issue and you can maybe follow the other issue? If you want I can also tag you in the other issue so that you are notified when I merge the PR. Let me know if that's ok. Thank you so much.

**Comment by Mallear** [comment]
That's fine for me :) thank you for your support

**Comment by Nadine2016** [comment]
thank you. :-) closing.
